from __future__ import annotations

import re

from uniswap_autopilot.common.common import CHAINS

HEX_DATA_RE = re.compile(r"^0x[0-9a-fA-F]*$")
CHAIN_BY_ID = {chain.chain_id: chain for chain in CHAINS.values()}
GLOBAL_RPC_ENV_CANDIDATES = ("ETH_RPC_URL", "RPC_URL")
APPROVE_SELECTOR = "0x095ea7b3"
DEFAULT_PRIVATE_KEY_ENV = "EXECUTOR_PRIVATE_KEY"
HOT_WALLET_PRIVATE_KEY_ENV_NAME = "HOT_WALLET_PRIVATE_KEY_ENV"
HOT_WALLET_KEYSTORE_ENV_NAME = "HOT_WALLET_KEYSTORE"
HOT_WALLET_ACCOUNT_ENV_NAME = "HOT_WALLET_ACCOUNT"
HOT_WALLET_PASSWORD_FILE_ENV_NAME = "HOT_WALLET_PASSWORD_FILE"
